Test.217
LoLProM/NeetCode pull request #2
Opened 2023-07-19 23:01 UTC by LoLProM

Mira a ver si esto llega

2023-07-19 23:27 UTC, andyguerra requested changes
Submission Result: Wrong Answer
Input: [1,2,3,1]
Output: false
Expected: true

Ni porque es el primer caso de ejemplo que sale en la descripción 🤦‍♂️

2023-07-19 23:54 UTC, andyguerra reviewed
**Success**
Runtime: 2628 ms, faster than 9.95% of C# online submissions for Contains Duplicate.
Memory Usage: 53.5 MB, less than 71.97% of C# online submissions for Contains Duplicate.

Ahora piensa una solución en orden O(N). La que tienes  ahora mismo es orden O(N^2)

Si no se te ocurre hoy mira este [vídeo](https://www.youtube.com/watch?v=3OamzN90kPg) con calma y sube la nueva solución

2023-07-19 23:57 UTC, LoLProM commented
ok la pensare voy a revisar en un momento el otro ejercicio

2023-07-21 02:23 UTC, andyguerra approved these changes
**Success**
Runtime: 218 ms, faster than 36.94% of C# online submissions for Contains Duplicate.
Memory Usage: 54.4 MB, less than 37.47% of C# online submissions for Contains Duplicate.

Compara la mejora... es notable la diferencia en tiempo de ejecución.

Lo hiciste tú solo o viste el vídeo?

Ya está aprobado, mezcla

2023-07-21 02:35 UTC, merged